version: '3'
services:
  node:
    user: node
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP_DIR: ${APP_DIR}
    container_name: apollo_universal_starter
    tty: true
    stdin_open: true
    command: >
      sh -c '
      yarn &&
      (test -f dev-db.sqlite3 || yarn seed) &&
      yarn watch
      '
    volumes:
      - ./:${APP_DIR}
      - ${APP_DIR}/build
      - ${APP_DIR}/node_modules
    working_dir: ${APP_DIR}
    ports:
      - 3000:3000
      - 8080:8080
